travis:
  secure:
    BINSTAR_TOKEN: N85mvphhTXeDkuWt+oWoue7f8O2i9A7r+FQ9RmF8KFrSXwCsxk5xN+/FaA2XWUo8PUpw9kTZGqlUFbD+2wey/g1aO5FL8EEMorG/k4CXvtuNx5bnYu42PIByifeOpNmRSuSQfqdxJvpfTyBgS5922UQpjtPfFXtlHZLF9nKWu5pF1FZykpycuwJbrWDfrVqdIcnZrb0jhNKvbY2Nob6GQ+cign2LmoJtn3eOQdnBTvSJsHh1d9AhKlgvSo/6S3RwEqnO4Zb/h8Tgwh6KImayBuSXCvCsm/N4cKSbBVqu1lIRnyskX6hglWxp8U0YoBuA53pvvTa34iV0QQfh81kAqqAUYJSj9Vreb0r9npW/+4CHlSfTO1R9D/rYZUeYcWa5djcV0sqvDtzosyMaz4Ah8KAadNFQFrFCXQJAIJ+i3+6TNL0+VdcI0W/LMm8QXcHG3ojo1MnkdKrf5PuPd6xW1XHoVJ9qx6y8d3IBcaaTC7angRhlD3v2z7iJKPo/S4yOQHUEUMmnlyOzqpiTrosqEP2UVjyJrXo1vcyua3Om8Mmd6mcNZ98JsXYHa4735w10SW0s8voji4tIm6KQ+z3385SS2Q4ow07ltbZvVU4yXiPO1PMS0ifnKVBqScry9o8eqLTPIWt1/4iJgKBAJe10KcHEUxTsfuwR5JE4SH1TS8Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
